Account_App/urls.py
from django.urls import path, re_path
from django.urls import reverse_lazy
from Account_App import views
from django.contrib.auth import views as auth_views
app_name = '[Account_App]'
urlpatterns = [
    path('add_data/', views.add_data, name='add_data'),

    path('login/', views.user_login, name="user_login"),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name="user_register"),
    path('password-change/', auth_views.PasswordChangeView.as_view(
        template_name='Account_App/password_change_form.html',
        success_url=reverse_lazy('Account_App:password_change_done')), name='password_change'),
    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='Account_App/password_change_done.html'), name='password_change_done'),
]

Book_App/urls.py
from django.urls import path, re_path

from Book_App import views

app_name = '[Book_App]'
urlpatterns = [
    path('book_seat/', views.book_seat, name='book_seat'),
    path('book_success/<table_id>/<time_id>/<date>/', views.book_success, name='book_success'),
    path('book_record/', views.book_record, name='book_record'),
    path('book_cancel/<reservation_id>/', views.book_cancel, name='book_cancel'),
]

Library_Reservation/urls.py
from django.contrib import admin
from django.urls import path, include
from Center_App import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('account/', include('Account_App.urls', namespace='account')),
    path('book/', include('Book_App.urls', namespace='book')),
    path('center/', include('Center_App.urls', namespace='center')),
    path('password-reset/', include('password_reset.urls')),

]

Account_App/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProf(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    icon = models.ImageField(upload_to='icon', default='icon/default_icon.jpg')  # 头像(有默认头像)
    credit = models.PositiveIntegerField(default=5)  # 信誉度
    delete_times = models.PositiveIntegerField(default=0)
    introduction = models.TextField(default="个人简介")  # 个人简介
    name = models.CharField(default="user", max_length=20)  # 姓名
    student_number = models.CharField(max_length=12)  # 学号
    phone_number = models.CharField(max_length=11)  # 电话号码
    record_id = models.TextField(editable=False)  # 预约记录

    class Meta:
        db_table = 'userprof'

    def __str__(self):
        return 'user {}'.format(self.user.username)

Account_App/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProf


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label="password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "email")

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("passwords do not match.")
        return cd['password2']


class UserProfForm(forms.ModelForm):
    class Meta:
        model = UserProf
        fields = ("phone_number",)

Account_App/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.urls import reverse

from .forms import LoginForm, RegistrationForm, UserProfForm

from .help_function import add_data_help


def user_login(request):
    if request.method == "POST":
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            cd = login_form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])

            if user:
                login(request, user)
                # 保存session记录
                request.session['user_id'] = user.id
                # 登录成功，定向至主页
                return redirect(reverse('center:homepage'))
            else:
                return HttpResponse("Sorry. Your username or password is not right.")
        else:
            return HttpResponse("Invaild login")

    if request.method == "GET":
        login_form = LoginForm()
        return render(request, "Account_App/login.html", {"form": login_form})


def logout(request):

    try:
        user_id = request.session.get('user_id')*1
    except Exception:
        return redirect(reverse('account:user_login'))

    request.session.flush()
    return redirect(reverse('account:user_login'))


def register(request):
    if request.method == "POST":
        user_form = RegistrationForm(request.POST)
        userpro_form = UserProfForm(request.POST)
        if user_form.is_valid() * userpro_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            new_pro = userpro_form.save(commit=False)
            new_pro.user = new_user
            new_pro.save()
            return redirect(reverse('account:user_login'))
        else:
            return HttpResponse("sorry, your can not register.")
    else:
        user_form = RegistrationForm()
        userpro_form = UserProfForm()

        return render(request, "Account_App/register.html", {"form": user_form, "pro": userpro_form})


def add_data(request):
    add_data_help()
    return HttpResponse('用户、座位添加成功')

templates/Account_App/login.html
{% extends 'base.html' %}

{% block title %}
      登录
{% endblock %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/account/css/login.css">
{% endblock %}


{% block invisible-header %}

    <div class="sticky">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <!-- Brand/logo -->
            <a class="navbar-brand" href="#">Logo.jpg</a>

            <!-- Links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="#">登陆</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">注册</a>
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}

{% block content %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="content" align="center">
        <br>
        <h1>Login</h1>
        <img border="0" src="/static/image/default_icon.bmp" alt="default_image" width="50" height="50">
        <br>
        <br>
        <p class="ex1" style="color:#C8C8C8">-Please input your username and password below.-</p>
        <br>
        <form class="form-horizontal" action="." method="post">{% csrf_token %}
            {{ form.as_p }}
            <div class="btn-group btn-group-sm">
                <a href=" ">
                    <button type="submit" class="btn btn-primary"
                            style="background-color: #203643;border-color: #cccccc">Login
                    </button>
                </a>
                <a href="{% url 'account:user_register' %}">
                    <button type="button" class="btn btn-primary"
                            style="background-color: #203643;border-color: #cccccc">Register
                    </button>
                </a>
            </div>
        </form>
        <br>
        <h5 style="font:small-caption">Forgot password?</h5>
        <h5 style="font:small-caption">Click <a href='{% url "password_reset_recover" %}'>here</a> to reset the password.</h5>
        <br>
    </div>


{% endblock %}

templates/Account_App/password_change_done.html
{% extends "base.html" %}
{% block title %}password change done{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <p>Your password was changed.</p>
</div>
{% endblock %}

templates/Account_App/password_change_form.html
{% block title %}password change{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>Change Password</h1>
    <p>Please enter your old password,for security's sake,and then enter your new password twice so we can verify you typed it in correctly.</p>
    {% if form.new_password1.help_text %}
     <div class="text-left" style="margin-left:400px">
      <p>{{ form.new_password1.help_text|safe }}</p>
     </div>
    {% endif %}
    <form class="form-horizontal" action="." method="post">{% csrf_token %}
        <div class="form-group">
            <label class='col-md-5 control-label text-right'>
                {{form.old_password.label_tag}}
            </label>
            <div class="col-md-6 text-left">{{ form.old_password }}</div>
        </div>

        <div class="form-group">
            <label class='col-md-5 control-label text-right'>
                {{form.new_password1.label_tag }}
            </label>
            <div class="col-md-6 text-left">{{ form.new_password1}}</div>
        </div>

        <div class="form-group">
            <label class="col-md-5 control-label text-right">
                {{form.new_password2.label_tag}}
            </label>
            <div class="col-md-6 text-left">{{form.new_password2}}</div>
        </div>
        <input type="submit" value="Change my password" class="btn btn-primary btn-lg"/>


    </form>
</div>
{% endblock %}

templates/Account_App/register.html
{% extends 'base.html' %}

{% block title %}
    注册
{% endblock %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/account/css/register.css">
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
{% endblock %}

{% load static %}


{% block content %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="content" align="center">
        <br>
        <h1>Register</h1>
        <img border="0" src="/static/image/default_icon.bmp" alt="default_image" width="50" height="50">
        <br>
        <br>
        <p class="ex1" style="color:#C8C8C8">-If you have already registered, here
            <strong><a href="{% url 'account:user_login' %}">Login</a></strong>.-
        </p>
        <br>
        <form class="form-horizontal" action="." method="post">{% csrf_token %}
            <div class="form-group">
                <label class="col-md-5 control-label">Username</label>
                <div class="col-md-6 text-left">{{ form.username }}</div>
            </div>
            <div class="form-group">
                <label class="col-md-5 control-label">Email</label>
                <div class="col-md-6 text-left">{{ form.email }}</div>
            </div>
            <div class="form-group">
                <label class="col-md-5 control-label">Password</label>
                <div class="col-md-6 text-left">{{ form.password }}</div>
            </div>
            <div class="form-group">
                <label class="col-md-5 control-label">Confirm Password</label>
                <div class="col-md-6 text-left">{{ form.password2 }}</div>
            </div>
            <div class="form-group">
                <label class="col-md-5 control-label">Phone</label>
                <div class="col-md-6 text-left">{{ pro.phone_number }}</div>
            </div>

            <div class="btn-group btn-group-sm">
                <a href=" ">
                    <button type="submit" class="btn btn-primary"
                            style="background-color: #203643;border-color: #cccccc">
                        Register
                    </button>
                </a>
            </div>
        </form>
        <br>
    </div>
{% endblock %}