Account_App/urls.py
from django.urls import path, re_path
from django.urls import reverse_lazy
from Account_App import views
from django.contrib.auth import views as auth_views
app_name = '[Account_App]'
urlpatterns = [
    path('add_data/', views.add_data, name='add_data'),

    path('login/', views.user_login, name="user_login"),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name="user_register"),
    path('password-change/', auth_views.PasswordChangeView.as_view(
        template_name='Account_App/password_change_form.html',
        success_url=reverse_lazy('Account_App:password_change_done')), name='password_change'),
    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='Account_App/password_change_done.html'), name='password_change_done'),
]

Book_App/urls.py
from django.urls import path, re_path

from Book_App import views

app_name = '[Book_App]'
urlpatterns = [
    path('book_seat/', views.book_seat, name='book_seat'),
    path('book_success/<table_id>/<time_id>/<date>/', views.book_success, name='book_success'),
    path('book_record/', views.book_record, name='book_record'),
    path('book_cancel/<reservation_id>/', views.book_cancel, name='book_cancel'),
]

Center_App/urls.py
from django.urls import path

from Center_App import views

app_name = '[Center_App]'
urlpatterns = [
    path('homepage/', views.homepage, name='homepage'),
    path('personal_center/', views.personal_center, name='personal_center'),
]

Library_Reservation/urls.py
from django.contrib import admin
from django.urls import path, include
from Center_App import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('account/', include('Account_App.urls', namespace='account')),
    path('book/', include('Book_App.urls', namespace='book')),
    path('center/', include('Center_App.urls', namespace='center')),
    path('password-reset/', include('password_reset.urls')),

]

templates/main/book.html
{% extends 'base_main.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}

{% endblock %}


{% block ext_js %}
    {{ block.super }}

{% endblock %}


{% block header %}
    <div class="banner">
        <div class="header">
            <div class="container">
                <div class="header-left">
                    <div class="w3layouts-logo">
                        <h1>
                            <a href="{% url 'center:homepage' %}"><span>SJTU</span> 图书馆预约 </a>
                        </h1>
                    </div>
                </div>
                <div class="header-right">
{#                    <div class="w3-header-top">#}
{#                        <ul>#}
{#                            <li><i class="fa fa-envelope" aria-hidden="true"></i> : <a href="mailto:info@example.com">lzh1633856298@gmail.com</a>#}
{#                            </li>#}
{#                        </ul>#}
{#                    </div>#}
                    <div class="w3-header-bottom">
                        <div class="top-nav">
                            <nav class="navbar navbar-default">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                            data-target="#bs-example-navbar-collapse-1">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>
                                <!-- Collect the nav links, forms, and other content for toggling -->
                                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                    <ul class="nav navbar-nav">
                                        <li><a href="{% url 'center:homepage' %}">主页</a></li>
                                        <li class=""><a class="active" href="#"
                                                        class="dropdown-toggle hvr-bounce-to-bottom"
                                                        data-toggle="dropdown" role="button" aria-haspopup="true"
                                                        aria-expanded="false">预约<span class="caret"></span></a>
                                            <ul class="dropdown-menu">
                                                <li><a class="hvr-bounce-to-bottom"
                                                       href="{% url 'book:books' %}">座位预约</a></li>
                                                <li><a class="hvr-bounce-to-bottom" href="{% url 'book:book_record' %}">预约记录</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li><a href={% url 'center:personal_center' %}>个人中心</a></li>
                                        <li><a href={% url 'account:logout' %}>退出</a></li>
                                    </ul>
                                    <div class="clearfix"></div>
                                </div>
                            </nav>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
{% endblock %}


{% block content %}
    <hr>
    <hr>
    <hr>
    <hr>
    <hr>
    <hr>
    <hr>
    <hr>
    <hr>
    <hr>
    <p class="text-center">座位预约</p>
    <hr>
    <hr>
    <hr>
    <hr>
    <hr>
    <hr>
    <hr>
    <hr>
    <hr>
    <hr>
    <hr>
    <hr>
    <hr>
    <hr>
{% endblock %}

templates/main/book_record.html
{% extends 'base_main.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="../../static/main/css/book_record.css">
{% endblock %}

{% block title %}
    预约记录
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script src="../../static/main/js/book_record.js"></script>
     <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
{% endblock %}


{% block header %}
    <div class="banner">
        <div class="header">
            <div class="container">
                <div class="header-left">
                    <div class="w3layouts-logo">
                        <h1>
                            <a href="{% url 'center:homepage' %}"><span>SJTU</span> 图书馆预约 </a>
                        </h1>
                    </div>
                </div>
                <div class="header-right">
                    <div class="w3-header-bottom">
                        <div class="top-nav">
                            <nav class="navbar navbar-default">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                            data-target="#bs-example-navbar-collapse-1">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>
                                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                    <ul class="nav navbar-nav">
                                        <li><a href="{% url 'center:homepage' %}">主页</a></li>
                                        <li class=""><a class="active" href="#"
                                                        class="dropdown-toggle hvr-bounce-to-bottom"
                                                        data-toggle="dropdown" role="button" aria-haspopup="true"
                                                        aria-expanded="false">预约<span class="caret"></span></a>
                                            <ul class="dropdown-menu">
                                                <li><a class="hvr-bounce-to-bottom" href="{% url 'book:book_seat' %}">座位预约</a>
                                                </li>
                                                <li><a class="hvr-bounce-to-bottom" href="{% url 'book:book_record' %}">预约记录</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li><a href={% url 'center:personal_center' %}>个人中心</a></li>
                                        <li><a href={% url 'account:logout' %}>退出</a></li>
                                    </ul>
                                    <div class="clearfix"></div>
                                </div>
                            </nav>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
{% endblock %}


{% block content %}

    <div class="text-center"><h1>预约记录</h1></div>
    <div class="text-center">
        <table class="table table-bordered" align="center" style="max-width: 800px;">
            <thead>
            <th width="15%" style="text-align:center">日期</th>
            <th width="15%" style="text-align:center">时间</th>
            <th width="15%" style="text-align:center">是否安静区</th>
            <th width="15%" style="text-align:center">座位编号</th>
            <th wdith="15%" style="text-align:center">状态</th>
            </thead>
            <tbody>
            {% for record in records_not_delete %}
                <tr>
                    <td><span>{{ record.day }}</span></td>
                    <td><span>{{ record.time_choice }}</span></td>
                    <td><span>{{ record.is_quiet }}</span></td>
                    <td><span>{{ record.seat_id }}</span></td>
                    <td>
                        <a class="CancelBooking" data-url="{% url 'book:book_cancel' reservation_id=record.id %}"><button class="button-default link">取消预约</button></a>
                    </td>
                </tr>
            {% endfor %}
            {% for record in records_is_delete %}
                <tr>
                    <td><span>{{ record.day }}</span></td>
                    <td><span>{{ record.time_choice }}</span></td>
                    <td><span>{{ record.is_quiet }}</span></td>
                    <td><span>{{ record.seat_id }}</span></td>
                    <td>已生效</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

templates/main/homepage.html
{% extends 'base_main.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
     <link rel="stylesheet" href="../../static/main/css/homepage.css">
{% endblock %}

{% block title %}
    主页
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script src="../../static/js/jquery.ripples-min.js"></script>
    <script src="../../static/main/js/homepage.js"></script>
{% endblock %}

{% block header %}
    <div class="banner">
        <div class="header">
            <div class="container">
                <div class="header-left">
                    <div class="w3layouts-logo">
                        <h1>
                            <a href="{% url 'center:homepage' %}"><span>SJTU</span> 图书馆预约 </a>
                        </h1>
                    </div>
                </div>
                <div class="header-right">
                    <div class="w3-header-bottom">
                        <div class="top-nav">
                            <nav class="navbar navbar-default">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                            data-target="#bs-example-navbar-collapse-1">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>
                                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                    <ul class="nav navbar-nav">
                                        <li><a class="active" href="{% url 'center:homepage' %}">主页</a></li>
                                        <li class=""><a href="#" class="dropdown-toggle hvr-bounce-to-bottom"
                                                        data-toggle="dropdown" role="button" aria-haspopup="true"
                                                        aria-expanded="false">预约<span class="caret"></span></a>
                                            <ul class="dropdown-menu">
                                                <li><a class="hvr-bounce-to-bottom" href="{% url 'book:book_seat' %}">座位预约</a>
                                                </li>
                                                <li><a class="hvr-bounce-to-bottom" href="{% url 'book:book_record' %}">预约记录</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li><a href={% url 'center:personal_center' %}>个人中心</a></li>
                                        <li><a href={% url 'account:logout' %}>退出</a></li>

                                    </ul>
                                    <div class="clearfix"></div>
                                </div>
                            </nav>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div>
        <section></section>
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="../../static/image/book.jpg" alt="firefox">
                    <div class="carousel-caption zi">
                        <h1>欢迎访问上海交通大学图书馆预约系统</h1>
                        <p>祝您拥有一段愉快而充实的学习时光</p>
                    </div>
                </div>
                <div class="item">
                    <img src="../../static/image/xintu.jpg" alt="firefox">
                </div>
                <div class="item">
                    <img src="../../static/image/baotu.jpg" alt="firefox">
                </div>
                <div class="item">
                    <img src="../../static/image/litu.jpg" alt="firefox">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">上一页</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">下一页</span>
            </a>
        </div>
        <div class="container">

            <!-- 水平线 -->
            <hr class="divider">
            <!-- 标签页 -->
            <ul class="nav nav-tabs" role="tablist" id="tab-list">
                <li role="presentation" class="active"><a href="#tab-chrome" aria-controls="home" role="tab"
                                                          data-toggle="tab">新图书馆</a></li>
                <li role="presentation"><a href="#tab-firefox" aria-controls="profile" role="tab"
                                           data-toggle="tab">李政道图书馆</a>
                </li>
                <li role="presentation"><a href="#tab-safari" aria-controls="messages" role="tab"
                                           data-toggle="tab">包玉刚图书馆</a>
                </li>
            </ul>
            <!-- 标签页下面的内容 -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="tab-chrome">
                    <div class="row feature">
                        <div class="col-md-7">
                            <h2 class="feature-heading">新图书馆</h2>
                            <p class="lead">
                                位于闵行校区中心位置的新馆于2006年3月11日奠基，服务面积约为3.5万平方米，在2008年9月试运行启用，12月15日正式开馆。新馆作为主馆，定位为“理工生医农综合馆”，在崭新的布局和设计上将充分体现图书馆全新的学科服务理念。
                                主馆座位近4000席。采用一门式管理模式，淡化书库和阅览室的界限，推行大开放、大服务的格局。 图书馆服务实现“藏、查、借、阅、参” 五位一体的有机服务机制；
                                延长服务时间，延伸服务场所；增加借还书、复印、扫描、打印等自助服务；主馆通过各种形式的创新服务，
                                为全校师生提供安静自习区、小组讨论室、课题研究室、多媒体试验区、多媒体制作室、多媒体演播室，
                                同时也提供外语自主学习中心，设计和构建具有主动生长特征的智能化综合服务设施，营造身临其境的学习研究氛围，成为能够容纳不同学习风格、研究习惯和使用需求的学术交流中心和信息共享空间。</p>
                        </div>
                        <div class="col-md-5">
                            <img class="feature-image img-responsive" src="/static/image/新图.png" alt="Chrome">
                        </div>
                    </div>
                </div>
                <div role="tabpanel" class="tab-pane" id="tab-firefox">
                    <div class="row feature">
                        <div class="col-md-5">
                            <img class="feature-image img-responsive" src="/static/image/李图.jpg" alt="Firefox">
                        </div>
                        <div class="col-md-7">
                            <h2 class="feature-heading">李政道图书馆</h2>
                            <p class="lead">
                                于2014年12月28日落成，由实体图书馆和“李政道数字资源中心”两大部分组成。
                                李政道图书馆开创性地实现了包括图书馆、档案馆、博物馆、科技馆和艺术馆在内的“五馆合一”的功能定位。
                                实体图书馆总建筑面积6,500平方米，分为地下一层，地上四层。地下一层为报告厅，有340个座位，可以举办各类学术会议及小型音乐会。
                                地上第一层和第二层的部分区域为展厅，在“以天之语，解物之道”的陈展主题下，共分为“问道”、“悟道”、“传道”和“超弦”四个展区。
                                第二层和第三层有2个阅览室，最大藏书容量约为7万册书刊，共有300余个阅览座位，5个小组讨论室。
                                第四层为李政道先生办公室、特藏书库和李政道研究所，收藏有各类李政道先生捐赠的珍贵档案藏品8万余件。
                                诺贝尔物理学奖获得者、著名物理学家李政道教授担任名誉馆长，李中清教授担任馆长。
                            </p>
                        </div>
                    </div>
                </div>
                <div role="tabpanel" class="tab-pane" id="tab-safari">
                    <div class="row feature">
                        <div class="col-md-7">
                            <h2 class="feature-heading">包玉刚图书馆</h2>
                            <p class="lead">
                                1992年，为适应上海交通大学办学规模的迅速发展，学校用包玉刚先生赠款建造包兆龙图书馆的节余部分及中国建设银行的资助，在闵行校区景色宜人的思源湖旁建造了一座新图书馆。正当学校筹备落成和开馆仪式之际，包玉刚先生不幸病逝。为对包玉刚先生表示永久的纪念，特将新落成的图书馆命名为包玉刚图书馆。
                                2008年9月，包玉刚图书馆定位为人文社科综合馆，位于闵行校区思源湖畔的包玉刚图书馆具有空间广阔的优势，以全新的理念进行设计和布局。在总体架构上采用借阅一体化管理模式，按学科分类并采用IC模式进行设置；同时结合文科院系的规模与特点，来规划空间与各类资源。总藏书量约为72万册，阅览座位约1200席。
                                参照新馆模式，人文社科综合馆实行一门式管理，一站式服务，推行大开放、大服务格局——大开间、全开架阅览。</p>
                        </div>
                        <div class="col-md-5">
                            <img class="feature-image img-responsive" src="/static/image/包图.png" alt="Safari">
                        </div>
                    </div>
                </div>

            </div>
            <!-- 水平线 -->
            <hr class="divider">
            <!-- 页脚 -->
        </div>
    </div>
{% endblock %}

templates/main/personal_center.html
{% extends 'base_main.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="../../static/main/css/personal_center.css">
{% endblock %}


{% block ext_js %}
    {{ block.super }}
{% endblock %}

{% block title %}
    个人中心
{% endblock %}

{% block header %}
    <div class="banner">
        <div class="header">
            <div class="container">
                <div class="header-left">
                    <div class="w3layouts-logo">
                        <h1>
                            <a href="{% url 'center:homepage' %}"><span>SJTU</span> 图书馆预约 </a>
                        </h1>
                    </div>
                </div>
                <div class="header-right">
                    <div class="w3-header-bottom">
                        <div class="top-nav">
                            <nav class="navbar navbar-default">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                            data-target="#bs-example-navbar-collapse-1">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>
                                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                    <ul class="nav navbar-nav">
                                        <li><a href="{% url 'center:homepage' %}">主页</a></li>
                                        <li class=""><a href="#" class="dropdown-toggle hvr-bounce-to-bottom"
                                                        data-toggle="dropdown" role="button" aria-haspopup="true"
                                                        aria-expanded="false">预约<span class="caret"></span></a>
                                            <ul class="dropdown-menu">
                                                <li><a class="hvr-bounce-to-bottom" href="{% url 'book:book_seat' %}">座位预约</a>
                                                </li>
                                                <li><a class="hvr-bounce-to-bottom" href="{% url 'book:book_record' %}">预约记录</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li><a class="active" href={% url 'center:personal_center' %}>个人中心</a></li>
                                        <li><a href={% url 'account:logout' %}>退出</a></li>

                                    </ul>
                                    <div class="clearfix"></div>
                                </div>
                            </nav>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
{% endblock %}


{% block content %}
    <script src="/static/js/jquery.js"></script>
    <script type="text/javascript">
        $(function () {
            //选项卡切换
            $('.category ul li').click(function () {
                indexC = $(this).index();
                $(this).addClass('active').siblings().removeClass('active');
                $('.cont').eq(indexC).addClass('active').siblings().removeClass('active');
            })
        })
    </script>


    <div class="panel panel-default" style="width:100%;">
        <div class="background0" style="height:300px;width:100%;list-style: none">
            <form method="post" enctype="multipart/form-data" action="{% url 'center:personal_center' %}">
                {% csrf_token %}
                <li>
                    <div style="width:20%;float:left;">
                        <div style="width:100px;height:100px;border-radius:75px;overflow:hidden;margin-left:150px;margin-top:100px;margin-bottom:80px;">
                            <img src="{{ icon }} " width="100px" height="100px">
                        </div>
                    </div>
                    <div style="width:80%;float:left;margin-top:80px;">
                        <h2>{{ name }}</h2>
                        <div class="form-group">
                            <input required style="float:left;clear:left;" name="icon" type="file" id="icon_input">
                        </div>
                        <button style="float:left;width:100px;height:30px;clear:left;margin-top:5px;" type="submit"
                                class="btn btn-success btn-block">上传头像
                        </button>
                    </div>
                </li>
            </form>
        </div>
    </div>

    <br>
    <br>

    <div class="container">
        <div class="category">
            <ul>
                <li class="active">基本信息</li>
                <li>信誉积分</li>
                <li>密码重置</li>
            </ul>
        </div>
        <div class="cont active">
            <ul>
                <li>
                    <div class="cont_main">
                        <h3 class="title">姓名</h3>
                        <p class="desc">{{ name }}</p>
                        <h3 class="title">电话</h3>
                        <p class="desc">{{ phone_number }}</p>
                        <h3 class="title">邮箱</h3>
                        <p class="desc">{{ mailbox }}</p>
                    </div>
                </li>
            </ul>
        </div>
        <div class="cont">
            <ul>
                <li>
                    <div class="cont_main">
                        <h3 class="title">信誉积分</h3>
                        <p class="desc">{{ credit }}分</p>
                        {% ifequal credit 0 %}
                            <p class="desc">{{ msg }}</p>
                        {% endifequal %}
                    </div>
                </li>
            </ul>
        </div>
        <div class="cont">
            <ul>
                <li>
                    <br>
                    <div class="cont_main">
                        <a class="desc" href='{% url "password_reset_recover" %}'>单击此处重置密码</a>
                    </div>
                    <br>
                </li>
            </ul>
        </div>
    </div>
    <br>
    <br>

{% endblock %}